frcking objects: 100% (5/5), 1.23 KiB | 78.00 KiB/s, done. From https://github.com/Johan-py/PropBol  * branch            develop    -> FETCH_HEAD     3efb6ac..3970d8d  develop    -> origin/develop     CONFLICT (modify/delete): bun.lock deleted in 34a8668 (fix: limpieza     total de dependencias y archivos de build) and modified in HEAD.     Version HEAD of bun.lock left in tree.     error: could not apply 34a8668... fix: limpieza total de     dependencias y archivos de build     hint: Resolve all conflicts manually, mark them as resolved with     hint: "git add/rm <conflicted_files>", then run "git rebase     --continue".     hint: You can instead skip this commit: run "git rebase --skip".     hint: To abort and get back to the state before "git rebase", run     "git rebase --abort".     fix: limpieza total de dependencias y archivos de build
    # Conflicts:
    #       bun.lock

    .git/COMMIT_EDITMSG [unix] (08:33 06/04/2026)
    1,1 Top
    "~/Documents/GitHub/PropBol/.git/COMMIT_EDITMSG" [unix] 18L, 580Bemote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 1.23 KiB | 78.00 KiB/s, done.
From https://github.com/Johan-py/PropBol
 * branch            develop    -> FETCH_HEAD
   3efb6ac..3970d8d  develop    -> origin/develop
CONFLICT (modify/delete): bun.lock deleted in 34a8668 (fix: limpieza total de dependencias y archivos de build) and modified in HEAD.  Version HEAD of bun.lock left in tree.
error: could not apply 34a8668... fix: limpieza total de dependencias y archivos de build
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
fix: limpieza total de dependencias y archivos de build

.git/COMMIT_EDITMSG [unix] (08:33 06/04/2026)                                             1,1 Top
"~/Documents/GitHub/PropBol/.git/COMMIT_EDITMSG" [unix] 18L, 580Bix: limpieza total de dependencias y archivos de build